server:
  port: 80

multipart:
  maxFileSize: 2Mb
  maxRequestSize: 2Mb

spring:
  profiles.active: development

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    enabled: true
    suffix: .html

  mail:
      host: smtp.gmail.com
      port: 587
      personal: Cruxer
      protocol: smtp
      tls: true
      properties.mail.smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

logging.level.org.springframework: INFO

error.whitelabel.enabled: false