server:
  port: 80

multipart:
  maxFileSize: 2Mb
  maxRequestSize: 2Mb

spring:
  profiles.active: development

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cruxer
    username: cruxer
    password: cruxer

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    enabled: true
    suffix: .html
    prefix: classpath:/

  mail:
      host: smtp.gmail.com
      port: 587
      personal: Cruxer
      username: #####
      password: #####
      protocol: smtp
      tls: true
      properties.mail.smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

logging.level.org.springframework: INFO

upload.file:
  url: http://localhost/files/
  path: files/
  charset: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  length: 25
